name: Snake Game CI

on:
  push:
    branches:
      - main  # Bu yerda 'main' branch nomini ko'rsatishingiz kerak
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the game
        run: python snake_game.py  # Bu yerda 'snake_game.py' fayli to'g'ri nom bilan yozilganligiga ishonch hosil qiling
